# modded hetashi
# Конфигурация Minecraft Manhunt

# Если true, при старте игры будет установлено дневное время
timeSetDayOnStart: true

# Если true, при старте игры погода будет ясной
weatherClearOnStart: true

# Длительность форы для спидраннеров в секундах
headStartDuration: 0

# Количество жизней у спидраннеров
speedrunnersLives: 1

# Если true, погибшие игроки перейдут в режим наблюдателя
spectatorAfterDeath: true

# Если true, игроки будут телепортированы друг к другу при старте игры
teleport: true

# Если true, охотники смогут отслеживать спидраннеров через порталы
trackPortals: true

# Если true, включен огонь по своим (friendly fire)
friendlyFire: true

# Если true, охотники могут использовать меню для выбора цели отслеживания
compassMenu: false

# Если true, охотники могут выбрать отслеживание ближайшего спидраннера
trackNearestMode: true

# Если true, инвентари будут очищены при старте игры
clearInventories: true

# Если true, игроки потеряют статус оператора при старте и получат его обратно после завершения
takeAwayOps: true

# Если true, только игроки с правами 'manhunt.help', 'manhunt.rules' и т.д. смогут использовать команды
usePermissions: false

# Если true, используется новый BossBar радар. Если false - стандартная подсветка (Locator Bar v1.21)
useBossBarRadar: false

# Если true, команды /manhunt pause и /manhunt unpause доступны
enablePauses: true

# --- Казуальный режим ---
# Включает способности охотников через компас (Shift + ПКМ)
casual: true

# Способность Shadows Warp
warpShadowsCooldown: 300
warpShadowsMaxDistance: 200
warpShadowsBufferZone: 40
